# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ZJUlesson/24Spring/CO/lab4/SOC/OExp02-IP2SOC.srcs/sources_1/ip/RAM_B/RAM_B.xci
# IP: The module: 'RAM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZJUlesson/24Spring/CO/lab4/SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/ZJUlesson/24Spring/CO/lab4/SOC/OExp02-IP2SOC.srcs/sources_1/ip/RAM_B/RAM_B.xci
# IP: The module: 'RAM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZJUlesson/24Spring/CO/lab4/SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
