# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/A7.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet
