# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ZJUlesson/24Spring/CO/lab2/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROM/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZJUlesson/24Spring/CO/lab2/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/ZJUlesson/24Spring/CO/lab2/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROM/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZJUlesson/24Spring/CO/lab2/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
